### ISSUE TITLE
Crouching if player is resized

### ISSUE THREAD

**Issue by edunad** [Metastruct/pac3#15]
I have no idea how long this bug exists, but to me its annoying.
If you change your player size and then crouch the camera goes down then teleports to the normal spot of the normal size.

**Comment by LUModder** [comment]
Might be a GMod bug?

**Comment by Techbot121** [comment]
I think I found the issue, let me try fixing it.

**Comment by Techbot121** [comment]
it's 4am and I should go to bed, anyway the issue is the check pac is doing here

https://github.com/Metastruct/pac3/blob/active/lua/pac3/core/shared/modifiers/size.lua#L17

if you remove the whole hooking stuff it works. Not sure why but that's how it is.

**Comment by suchipi** [comment]
@Python1320 those lines seem to be related to your Testing PlayerSlowThink (commit ef76ee58b6f8ad262f2cac8b146a2ad1692b0fdf). Do you have any insight to shed on this? I do know that the crouching height reset bug existed before your commit, though.

**Comment by Techbot121** [comment]
I tried it with caps only version without the crashfix and it was still there.

Also I was experimenting with the SetViewOffsetDucked and it turns out that you can just set it on server and it works fine too.

**Comment by Techbot121** [comment]
Ok I did some more testing. I tried just setting SetViewOffsetDucked on Tick and that worked fine, but as soon as I used pac.SetPlayerScale it fucked up until I removed the hook.

**Comment by Techbot121** [comment]
okay pinpointed it to the "ply:SetModelScale(safe, 0)" line if you comment out it works fine.

**Comment by Techbot121** [comment]
yeah upon further testing it seems to be the Server side "ply:SetModelScale" on line 64 that causes the issue if you comment that out it works fine

**Comment by suchipi** [comment]
If we don't set the player scale on the server, though, won't changes in size not be perceived by other users?

**Comment by edunad** [comment]
probably :<

**Comment by Techbot121** [comment]
no I mean like the hook that calls it on think, if you run pac.SetPlayerSize it still works fine, Failcake was on my server and it did work.

**Comment by Techbot121** [comment]
http://pastebin.com/E5AX8aPw this is what we used to test it on pythons server, it works fine, but the SetHullDuck, which should be fixed in the dev branch

**Comment by suchipi** [comment]
I don't really understand; can this be fixed with a PR now or are we waiting on something on the GarrysMod side?

**Comment by suchipi** [comment]
Also, @PotcFdk posted this elsewhere, not sure if it holds relevance? http://facepunch.com/showthread.php?t=1374457&p=46016660&viewfull=1#post46016660

**Comment by Techbot121** [comment]
not anymore http://facepunch.com/showthread.php?t=1450721&p=47462684&viewfull=1#post47462684

**Comment by Techbot121** [comment]
also that was me posting it first :new_moon_with_face:

**Comment by PotcFdk** [comment]
So it's fixed in the dev branch?

**Comment by edunad** [comment]
<3

**Comment by PotcFdk** [comment]
I'll take that as a yes.

**Comment by edunad** [comment]
This is still an issue, even with the new gmod update that stated a fix.

**Comment by Techbot121** [comment]
yea noticed it happening again

**Comment by Techbot121** [comment]
might be related
http://facepunch.com/showthread.php?t=1450721&p=47913629&viewfull=1#post47913629

**Comment by PotcFdk** [comment]
Quoting [this](http://www.garrysmod.com/2015/12/16/december-2015-update/), might be related:
>Fixed prediction errors when walking or attempting to sprint while crouched

**Comment by LUModder** [comment]
Yep, that seems to have fixed it. Just tested it and it's not popping me back up with 0.1 size when I crouch so it should work with other sizes

**Comment by Python1320** [comment]
https://github.com/Metastruct/pac3/commit/c4d11462255bb8c48595b39b6be5b29ad6189d01
